title = "metadata for oscar CI run"

[env]
# os = [ "ubuntu-latest" ]
# julia-version = [ "~1.6.0-0" ]
# branches = [ "<matching>", "release" ]

[pkgs]
  [pkgs.Nemo]
  test = false

  [pkgs.Hecke]
  test = true
