#! /bin/sh
cd src

export LD_LIBRARY_PATH=/home/wbhart/mpir-2.7.0/.libs:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/wbhart/mpfr-3.1.2/src/.libs:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/wbhart/flint2:$LD_LIBRARY_PATH

julia --quiet

